version: "3.7"

services:
  worker: 
    container_name: loganalytics-worker
    build: .
    ports:
      - 8890:8890
    restart: always     
    networks:
      - docker-network
    
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "loganalyticsdb"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - docker-network

networks:
    docker-network: 
      name: docker-network
    
